// <auto-generated />
using BookStore.EFModels.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStore.EFModels.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookStore.EFModels.Model.BookDetails", b =>
                {
                    b.Property<int>("book_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("author_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("book_count")
                        .HasColumnType("int");

                    b.Property<string>("book_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("publisher_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("book_id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookStore.EFModels.Model.BuyerDetails", b =>
                {
                    b.Property<int>("IndexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("book_id")
                        .HasColumnType("int");

                    b.Property<string>("buyer_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("buyer_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IndexId");

                    b.ToTable("Buyer");
                });
#pragma warning restore 612, 618
        }
    }
}
